services:
  - type: web
    name: stock-for-pymes-api
    runtime: docker
    dockerfilePath: apps/api/Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-for-pymes-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "8h"
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "https://project-ifp.vercel.app"
    healthCheckPath: /api/health

databases:
  - name: stock-for-pymes-db
    plan: free
    databaseName: stock_for_pymes
    region: frankfurt
